spring.application.name=SB07DataJPAExtras

spring.datasource.url= jdbc:mysql://localhost:3306/Day41EmployeeDB
spring.datasource.username=root
spring.datasource.password=#Sarthak@76342

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
