spring.application.name=SB10StudenCourseSystem

spring.datasource.url= jdbc:mysql://localhost:3306/Day42StudentCourseDB
spring.datasource.username= root
spring.datasource.password= #Sarthak@76342

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true

