spring.application.name=order-service

server.port=8081

management.tracing.sampling.probability=1.0
zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

logging.pattern.level= "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

# Enable health indicator
resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true

# Sliding window size
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5

# Minimum number of calls before calculating failure rate
resilience4j.circuitbreaker.instances.paymentService.minimumNumberOfCalls=3

# Failure rate threshold (in percentage)
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50

# Time circuit stays OPEN before going to HALF-OPEN
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10s

# Number of calls allowed in HALF-OPEN state
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=2