spring.application.name=SB11SpringSecurity


spring.datasource.url= jdbc:mysql://localhost:3306/Day43SecurityDB
spring.datasource.username= root
spring.datasource.password= #Sarthak@76342

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true

